apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c29tZXJvb3RwYXNzd29yZA==  # base64-encoded "somerootpassword"
  MYSQL_USER: dGVzdHVzZXI=                       # base64-encoded "testuser"
  MYSQL_PASSWORD: dGVzdHBhc3N3b3Jk               # base64-encoded "testpassword"
